@startuml
title Механизм заказа банковской карты

|Клиент|
start
:POST/cards;

|#AntiqueWhite|Сервер|
if (Тип заказа?) then (Перевыпуск)
|Клиент|
:Указать причину;
else (Первичный выпуск)
|#AntiqueWhite|Сервер|
:GET/retail-banking/accounts;
  
 if (Счёт найден?) then (Нет)
 |Клиент|
 :Предлагается открыть счёт;
  if (Клиент согласен?) then (Нет)
  :400 Bad Request;  
  end
  endif
 endif
|#AntiqueWhite|Сервер|
:POST/accounts;
:201 Created;

endif

|Клиент|
:POST/delivery-address;

|#AntiqueWhite|Сервер|
:Проверка валидации данных;
if (Данные корректны?) then (Нет)
|Клиент|
:400 Bad Request;
end

else (Да)
|#AntiqueWhite|Сервер|
:Создается заявка в БД;
endif

|Клиент|
:Пройти двухфакторную аутентификацию 2FA;

|#AntiqueWhite|Сервер|

repeat

:Проверка 2FA;
if (2FA успешна?) then (Нет)
else (Да)
:Отправить заявку в Kafka;
|Клиент|
:200 OK;
stop
endif

repeat while (Попыток больше трех?) is (Нет)not (Да)

|Клиент|
:401 Unauthorized;
end

@enduml

