@startuml
title Механизм заказа банковской карты

|Клиент|
start
:POST/cards;

|#AntiqueWhite|Сервер| 
if (Тип заказа?) then (Перевыпуск)
|Клиент|
:Указывается причина;
else (Первичный выпуск)
|#AntiqueWhite|Сервер|
:GET/retail-banking/accounts;
  
 if (Счёт найден?) then (Нет)
 |Клиент|
 
  :404 Not Found
  "Для выпуска необходим 
  активный счет";  
  end
else (Да) 
|#AntiqueWhite|Сервер|
:Привязывается счет;

endif
endif

|Клиент|
repeat
:POST/delivery-address;

|#AntiqueWhite|Сервер|
:Проверяется валидация данных;

repeat while (Данные корректны?) is (Нет)not (Да)


|#AntiqueWhite|Сервер|
:Создается заявка в БД;


|Клиент|
:Предлагается пройти двухфакторную аутентификацию 2FA;

|#AntiqueWhite|Сервер|

repeat

:Проверяется 2FA;
if (2FA успешна?) then (Нет)
else (Да)

fork
:Отправляется заявка в Kafka;
fork again
|Клиент|
:200 OK;
end fork

stop
endif

|#AntiqueWhite|Сервер|

repeat while (Попыток больше трех?) is (Нет)not (Да)

|Клиент|
:401 Unauthorized;
end

@enduml

