@startuml  

entity Card_order
{  
card_order_id <<PK>> 

customer_id
product_id: <<FK>> 
status
created_at
updated_at
} 

entity Address 
{

card_order_id: <<PK>> 
country
city
street
house_number
apartment
comment
created_at
updated_at
}

entity Product
{
product_id: <<PK>> 

name:
product_type
cashback
created_at
updated_at
}

entity Card
{

card_order_id <<PK>> 
card_name
card_number
expiry_date
cvv
issue_date
status
created_at
updated_at
}

Card_order ||--|| Address
Product ||--o{ Card_order
Card_order ||--|| Card

@enduml
