@startuml  

entity Card_order
{  
card_order_id: UUID "RK"

customer_id: uuid 
product_id: uuid "FK"
status: varchar(20)
created_at: timestamp
updated_at: timestamp
} 

entity Address 
{
address_id: UUID "RK"

card_order_id: uuid "FK"
country: varchar(50)
city: varchar(50)
street: varchar(200)
house_number: varchar(10)
apartment: varchar(10)
comment: varchar(200)
created_at: timestamp
updated_at: timestamp
}

entity Product
{
product_id: UUID "RK"

name: varchar(100)
product_type: varchar(20)
cashback: varchar(50)
created_at: timestamp
updated_at: timestamp
}

entity Card
{
card_id: UUID "RK"

card_order_id: uuid "FK"
card_name: varchar(200)
card_number: varchar(19) 
expiry_date: date
cvv: varchar(3)
issue_date: timestamp
status: varchar(20)
}

Card_order ||--|| Address
Product ||--o{ Card_order
Card_order ||--|| Card